-- Synthetic local reproduction of the reviewed live trigger chain; NEVER deploy.
BEGIN;
DO $guard$ BEGIN
 IF current_database() !~ '^buildtrack_sales_runtime_[a-f0-9]+$'
 OR current_user !~ '^runtime_[a-f0-9]+$'
 OR current_setting('buildtrack.synthetic_runtime',true) IS DISTINCT FROM 'on'
 OR inet_server_addr() IS DISTINCT FROM '127.0.0.1'::inet
 OR EXISTS(SELECT 1 FROM crm_external_private.booking_writer_releases)
 THEN RAISE EXCEPTION 'CONSTRUCTION_SYNTHETIC_RUNTIME_REQUIRED'; END IF;
END; $guard$;
-- plots.house_type_id and its reviewed FK already exist in the full shared fixture.
CREATE TABLE public.task_templates(id uuid PRIMARY KEY,house_type_id uuid,task_name text NOT NULL,
 task_order integer NOT NULL,is_progress_counted boolean DEFAULT true);
CREATE TABLE public.plot_task_assignments(id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 plot_id text,task_template_id uuid,current_progress integer DEFAULT 0,actual_start_date timestamptz,
 actual_end_date timestamptz,latest_action text,latest_role text,latest_update_created_at timestamptz,
 UNIQUE(plot_id,task_template_id));
ALTER TABLE public.task_updates ADD COLUMN id uuid DEFAULT gen_random_uuid(),
 ADD COLUMN plot_id text,ADD COLUMN task_template_id uuid,ADD COLUMN role text,ADD COLUMN action text,
 ADD COLUMN progress integer DEFAULT 0,ADD COLUMN created_at timestamptz DEFAULT now();
ALTER TABLE public.defects ADD COLUMN plot_id text,ADD COLUMN task_id uuid,
 ADD COLUMN task_template_id uuid,ADD COLUMN progress integer;
ALTER TABLE public.house_types ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.task_templates ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.plot_task_assignments ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON public.house_types,public.task_templates,public.plot_task_assignments FROM PUBLIC,anon,authenticated,service_role;
INSERT INTO public.house_types(id,type_name) VALUES('c0290000-0000-4000-8000-000000000001','SYNTHETIC counted home');
INSERT INTO public.task_templates(id,house_type_id,task_name,task_order,is_progress_counted) VALUES
 ('c0290000-0000-4000-8000-000000000011','c0290000-0000-4000-8000-000000000001','SYNTHETIC counted',1,true),
 ('c0290000-0000-4000-8000-000000000012','c0290000-0000-4000-8000-000000000001','SYNTHETIC nullable counted',2,NULL),
 ('c0290000-0000-4000-8000-000000000013','c0290000-0000-4000-8000-000000000001','SYNTHETIC ignored',3,false);
INSERT INTO public.plots(id,project_name,foreman_name,plot_name,has_customer,sale_status,house_type_id)
 SELECT 'SYNTHETIC-CONSTRUCTION-'||v.name,'PROJECT A','SYNTHETIC foreman','SYNTHETIC '||v.name,v.occupied,v.status,
 'c0290000-0000-4000-8000-000000000001'::uuid
 FROM (VALUES ('vacant',false,'active'),('incomplete',false,'active'),
 ('transferred',true,'transferred'),('transferred-vacant',false,'transferred'),
 ('bulk-one',false,'active'),('bulk-two',false,'active')) v(name,occupied,status);
CREATE OR REPLACE FUNCTION public.update_task_progress_trigger()
 RETURNS trigger
 LANGUAGE plpgsql
AS $function$
DECLARE
    v_plot_id TEXT;
    v_task_template_id UUID;
    min_start TIMESTAMPTZ;
    max_end TIMESTAMPTZ;
    latest_progress INTEGER;
    v_latest_action TEXT;
    v_latest_role TEXT;
    v_latest_created_at TIMESTAMPTZ;
BEGIN
    IF TG_OP = 'DELETE' THEN
        v_plot_id := OLD.plot_id::text;
        v_task_template_id := OLD.task_template_id::uuid;
    ELSE
        v_plot_id := NEW.plot_id::text;
        v_task_template_id := NEW.task_template_id::uuid;
    END IF;

    SELECT progress, action, role, created_at 
    INTO latest_progress, v_latest_action, v_latest_role, v_latest_created_at
    FROM task_updates
    WHERE plot_id::text = v_plot_id AND task_template_id = v_task_template_id
    ORDER BY created_at DESC
    LIMIT 1;

    IF latest_progress = 100 THEN
        SELECT MAX(created_at) INTO max_end
        FROM task_updates
        WHERE plot_id::text = v_plot_id AND task_template_id = v_task_template_id
          AND progress = 100;
    ELSE
        max_end := NULL;
    END IF;

    IF COALESCE(latest_progress, 0) = 0 THEN
        min_start := NULL;
    ELSE
        SELECT MIN(created_at) INTO min_start
        FROM task_updates
        WHERE plot_id::text = v_plot_id AND task_template_id = v_task_template_id
          AND progress > 0;
    END IF;

    INSERT INTO plot_task_assignments (
        plot_id, task_template_id, current_progress, actual_start_date, actual_end_date,
        latest_action, latest_role, latest_update_created_at
    )
    VALUES (
        v_plot_id, v_task_template_id, COALESCE(latest_progress, 0), min_start, max_end,
        v_latest_action, v_latest_role, v_latest_created_at
    )
    ON CONFLICT (plot_id, task_template_id)
    DO UPDATE SET 
        current_progress = EXCLUDED.current_progress,
        actual_start_date = EXCLUDED.actual_start_date,
        actual_end_date = EXCLUDED.actual_end_date,
        latest_action = EXCLUDED.latest_action,
        latest_role = EXCLUDED.latest_role,
        latest_update_created_at = EXCLUDED.latest_update_created_at;

    RETURN NULL;
END;
$function$
;
CREATE TRIGGER trigger_update_task_progress AFTER INSERT OR DELETE OR UPDATE ON public.task_updates FOR EACH ROW EXECUTE FUNCTION update_task_progress_trigger();
CREATE OR REPLACE FUNCTION public.auto_update_plot_sale_status()
 RETURNS trigger
 LANGUAGE plpgsql
AS $function$
DECLARE
    v_plot_id VARCHAR; -- แก้จาก UUID เป็น VARCHAR
    v_total_counted_tasks INT;
    v_completed_counted_tasks INT;
    v_has_customer BOOLEAN;
BEGIN
    IF TG_OP = 'DELETE' THEN
        v_plot_id := OLD.plot_id;
    ELSE
        v_plot_id := NEW.plot_id;
    END IF;

    SELECT COUNT(*) INTO v_total_counted_tasks
    FROM task_templates
    WHERE house_type_id = (SELECT house_type_id FROM plots WHERE id = v_plot_id)
      AND (is_progress_counted = true OR is_progress_counted IS NULL);

    SELECT COUNT(*) INTO v_completed_counted_tasks
    FROM plot_task_assignments pta
    JOIN task_templates tt ON pta.task_template_id = tt.id
    WHERE pta.plot_id = v_plot_id 
      AND pta.current_progress >= 100
      AND (tt.is_progress_counted = true OR tt.is_progress_counted IS NULL);

    SELECT has_customer INTO v_has_customer
    FROM plots WHERE id = v_plot_id;

    IF v_total_counted_tasks > 0 AND v_completed_counted_tasks = v_total_counted_tasks THEN
        IF v_has_customer = TRUE THEN
            UPDATE plots SET sale_status = 'transferred' WHERE id = v_plot_id AND sale_status != 'transferred';
        ELSE
            UPDATE plots SET sale_status = 'ready_for_sale' WHERE id = v_plot_id AND sale_status != 'ready_for_sale';
        END IF;
    END IF;

    RETURN NULL;
END;
$function$
;
CREATE TRIGGER auto_update_plot_sale_status_trigger AFTER UPDATE OF actual_end_date ON public.plot_task_assignments FOR EACH ROW WHEN (((old.actual_end_date IS DISTINCT FROM new.actual_end_date) AND (new.actual_end_date IS NOT NULL))) EXECUTE FUNCTION auto_update_plot_sale_status();
CREATE OR REPLACE FUNCTION public.sync_defect_progress()
 RETURNS trigger
 LANGUAGE plpgsql
AS $function$
BEGIN
  -- ทำงานเฉพาะเมื่อเปอร์เซ็นต์ (current_progress) มีการเปลี่ยนแปลง
  IF NEW.current_progress IS DISTINCT FROM OLD.current_progress THEN
    UPDATE defects 
    SET progress = NEW.current_progress
    WHERE plot_id::text = NEW.plot_id::text
      AND (
        task_id::text = NEW.task_template_id::text 
        OR task_template_id::text = NEW.task_template_id::text
      );
  END IF;
  RETURN NEW;
END;
$function$
;
CREATE TRIGGER on_assignment_progress_change AFTER UPDATE ON public.plot_task_assignments FOR EACH ROW EXECUTE FUNCTION sync_defect_progress();
COMMIT;

